url: http://arufonsekun.github.io

baseurldev: "localhost:4000"

title: Junior Vitor Ramisch - Computer Science Student

overview: My name is Junior Vitor Ramisch, I'm a Computer Science Undergraduate from Federal University of Fronteira Sul - UFFS Chapec√≥. The things that I enjoy the most from computer science is Web Development, Computer Vision and Machine Learning. 

githubdescription: Technical degree by IFC Concordia and Computer Science Undergraduate by Federal University of Fronteira Sul, has some skills in Web development, novice in computer vision.

avatar: https://avatars2.githubusercontent.com/u/19571204?s=400&u=39ac504de6b92527dfff611c6df9252f2320603e&v=4